Dev
harttle/md-padding pull request #25
Opened 2023-12-27 05:43 UTC by obgnail

2023-12-27 05:51 UTC, obgnail commented
开发者你好。修复三个问题：

## fix ordered-list-item isValidPrefix
问题：

有序列表的判断有误。

## fix parse: reset blockCodeDelimiter at BlockCode
问题：

parse中的FrontMatter处理逻辑会设置 blockCodeDelimiter，而 BlockCode 没有，导致 blockCodeDelimiter 有误
```ts
    else if (c3 === '```' && allow(NodeKind.BlockCode)) {
      push(State.BlockCodeLang)
      i += 3
    }
    else if (c3 === '---' && allowFrontMatter()) {
      push(State.BlockCodeLang)
      blockCodeDelimiter = c3
      i += 3
    }
```

复现文本:
````markdown
---
test:1
---

```js
console.log(1)
```
````

## fix node-kind: add Math into Inline
问题：

Math 支持 inline 模式，但是没有加入到 inline 变量中

复现文本：
```markdown
- 前$Latex$后
```

2023-12-27 13:54 UTC, harttle requested changes
感谢一起改这个东西，我来帮忙修流水线和发布

2023-12-27 13:54 UTC, harttle commented on src/nodes/ordered-list-item.ts
> +    return isNumeric(str[0]) && str[1] === '.' && str[2] === ' '
建议用 `isBlank`，因为我猜测 `\t` 也是合法的。

```suggestion
    return isNumeric(str[0]) && str[1] === '.' && isBlank(str[2])
```

2023-12-27 13:54 UTC, harttle commented on src/parser/parse.ts
> +      blockCodeDelimiter = c3
nit: 能否把 PR 描述中提到的复现代码，以 test case 的形式添加到 parse.spec.ts 中？

2023-12-27 13:55 UTC, harttle commented on src/nodes/node-kind.ts
> +  Inline = NaturualConstructs | InlineCode | Link | Style | HTMLTag | InlineImage | ReferenceImage | Math,
nit: 同样地，能否把复现文本也添加到对应的 test case 里。

2023-12-27 15:37 UTC, obgnail commented
@harttle 开发者你好，已经加了 testcase。您看一下。

`'when there is front matter, the delimiter of the code block should be ``` instead of ---'` 这个 testcase 会比较奇怪，因为此时 bug 的情况是 ``` 会被修改成 ---

isBlank 的修改可能需要交还给您处理了，我看了下代码，quote，ordered list，unordered list 使用的都是 " "，需要统一修改。

2023-12-27 15:38 UTC, obgnail commented on src/nodes/ordered-list-item.ts
> +    return isNumeric(str[0]) && str[1] === '.' && str[2] === ' '
这个修改可能需要交还给您处理了，我看了下代码，quote，ordered list，unordered list 使用的都是 " "，需要统一修改。

2023-12-27 16:42 UTC, obgnail commented on src/nodes/ordered-list-item.ts
> +    return isNumeric(str[0]) && str[1] === '.' && str[2] === ' '
GPT：实际上，Markdown 对于无序列表的格式是比较宽松的，可以使用破折号后面的空格或者制表符来表示列表项。所以你可以把【- abc】换成【-\tabc】，Markdown 都会正确地将其解析为无序列表的一部分。

2023-12-28 04:26 UTC, harttle approved these changes

2023-12-28 04:26 UTC, merged

2023-12-28 06:38 UTC, harttle commented
vscode extension published: https://github.com/harttle/md-padding-vscode/commit/c7fcf6ee4b0ee52d851317edcabdfb040039138b