parse blockquote
harttle/md-padding pull request #27
Opened 2024-01-06 14:20 UTC by obgnail

fix [issue](https://github.com/harttle/md-padding/issues/26)

2024-01-06 14:41 UTC, obgnail commented on src/parser/parse.ts
> +      continue
BlockquoteItem 允许嵌套 UnorderListItem、orderListItem、blockquoteItem。

因此，遇到 BlockquoteItem 后，应该依旧视为 blankLine，故直接 continue，防止 blankLine 被置为 false

2024-01-07 06:09 UTC, harttle requested changes

2024-01-07 06:09 UTC, harttle commented on src/parser/state.ts
> +  BlockquoteItem,     // ><space>
我试了几个编辑器，看起来 space 是不需要的

2024-01-07 06:13 UTC, harttle commented on test/parser/parse.spec.ts
> +      const doc = parse('> * **测试**', options)
好奇对于 `> > 测试` 会怎样，如果确实有问题的话：建议增加这一个测试，用 `stateMasks` 来解决。

2024-01-07 12:54 UTC, obgnail commented
@harttle 开发者你好，不好意思，我下午被 `i need you there` 了，现在才有时间，刚刚快速处理了一下，麻烦看一下

2024-01-07 15:57 UTC, harttle requested changes

2024-01-07 15:57 UTC, harttle commented on src/parser/parse.ts
> +      }
这一段应该可以干掉，因为1）我们不确定后面跟着多少空格，2）在 toMarkdown 后这些空格应该予以保留（去空格的操作应该发生在后续的过程中，不应该发生在parse过程）

产生的结果中确实会存在额外的空格，我觉得这是合理的。比如 `> foo` 应该要解析为 `BlockQuote{ Blank, AlphabetNumeric }`

我给既有的 OrderedListItem 也加了个测试供参考： https://github.com/harttle/md-padding/blob/135c79c455a4ee2a20b2204d6aaca53de1b198f1/test/parser/parse.spec.ts#L583-L603

2024-01-07 17:46 UTC, obgnail commented
@harttle 

开发者你好，已修复，麻烦再 review 一下

我确实没想到 markdown 的语法这么宽松 👍

---

问一个无关问题，为什么 lint 检测总是会失效？因为 windows 平台吗？（我平时不写 web js/ts，不太懂这个）

![Snipaste_2024-01-08_01-33-29](https://github.com/harttle/md-padding/assets/48992887/ef9a02f7-3343-49a9-afae-f32c2949bd9e)
![Snipaste_2024-01-08_01-32-10](https://github.com/harttle/md-padding/assets/48992887/a6162de9-598b-406e-89c6-523c072a002a)

2024-01-07 18:02 UTC, harttle approved these changes

2024-01-07 18:02 UTC, merged

2024-01-07 18:06 UTC, harttle commented
@obgnail 不确定，我猜测有可能是 `**/*.ts` 依赖 Shell 展开，在 PowerShell 或 CMD 里不一定支持，可能应该写成 `eslint 'src/**/*.ts'`